apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "project-name-ecr"
  description: 
  annotations:
    github.com/project-slug: shujaahmedi2l/project-name-ecr
    argocd/app-name: project-name-ecr
  links:
    - url: https://project-name-ecr.onexidp.com
      title: Web Application
      icon: LaunchIcon
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
